spring:
  datasource:
    url: jdbc:mysql://192.168.0.249:3306/besta?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 3
    password:
#logging:
  #config: http://10.20.13.16:8888/*/default/master/logback-spring.xml
  #path: D:/Temp/logs/
