spring:
  datasource:
    url: jdbc:mysql://192.168.1.5:3307/besta?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Tao@2018
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: 192.168.1.5
    port: 6379
    database: 0
    password:
logging:
  config: http://192.168.1.10:8888/*/default/master/logback-spring.xml
  path: C:/Users/Tao/Downloads/temp/logs/
