spring:
  datasource:
    url: jdbc:mysql://172.16.190.86:3306/besta_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: shuma
    password: q1w2E#R$
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  redis:
    host: 172.16.190.86
    port: 6379
    database: 0
    password:
logging:
  level:
    com.hoperun: debug